Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder ".", "/vagrant_data", disabled: true
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.linked_clone = true
      vb.memory = 2048
    end
    
    config.vm.define "ubuntu1" do |ubuntu1|
        ubuntu1.vm.hostname = "ubuntu-docker"
    end
    
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
      end
  end