apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostPath-local-web
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hostPath-local-web
  template:
    metadata:
      labels:
        app: hostPath-local-web
    spec:
      containers:
      - name: hostPath-local-web
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: local
          mountPath: /usr/share/nginx/html
      volumes:
      - name: local
        hostPath:
          path: /var/nginx-data