apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-name
  namespace: namespace
  labels:
    app: namespace
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: #Pilih StorageClass yang dipakai
  resources:
    requests:
      storage: 10Gi

  # ---
  # Digital Ocean
  # storageClassName: do-block-storage
  # ---
  # AWS
  # storageClassName: aws-ebs
  # ---
  # Azure
  # storageClassName: azure-disk
  # ---
  # GCE PD
  # storageClassName: gce-pd
  # ---