IMAGE_NAME = "ubuntu/bionic64"
N = 2

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        echo "10.10.10.10  master-node" >> /etc/hosts
        echo "10.10.10.11  worker-node-01" >> /etc/hosts
        echo "10.10.10.12  worker-node-02" >> /etc/hosts
    SHELL
  
    config.vm.box = IMAGE_NAME
    config.vm.box_check_update = true
  
    config.vm.define "master" do |master|
      # master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "master-node"
      master.vm.network "private_network", ip: "10.10.10.10"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 2621
          vb.cpus = 2
      end
      master.vm.provision "shell", path: "k8s-setup/setup.sh"
      master.vm.provision "shell", path: "k8s-setup/master.sh"
    end
  
    (1..N).each do |i|
  
    config.vm.define "node-0#{i}" do |node|
      # node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "worker-node-0#{i}"
      node.vm.network "private_network", ip: "10.10.10.1#{i}"
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 1
      end
      node.vm.provision "shell", path: "k8s-setup/setup.sh"
      node.vm.provision "shell", path: "k8s-setup/worker.sh"
    end
  
    end
  end 